services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./PGData:/var/lib/postgresql/data

  web-app:
    image: web-app:latest
    container_name: web-app
    build: 
      context: ./Mysite
      dockerfile: ./Dockerfile-dev
    restart: always
    command: bash docker-entrypoint-dev.sh

    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - mode=${mode}
    ports:
     - "8888:8000"
    volumes:
      - ./Mysite:/app
    depends_on:
      - db