services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./PGData:/var/lib/postgresql/data
    networks:
      - my_network

  web-app:
    container_name: web-app
    build: 
      context: ./Mysite
      dockerfile: ./Dockerfile-dev
    restart: always
    entrypoint: /app/docker-entrypoint-product.sh
    command: uwsgi --ini uwsgi.ini

    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - mode=${mode}
    volumes:
      - ./Mysite:/app
    depends_on:
      - db
    networks:
      - my_network

  nginx:
    container_name: nginx-container
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Mysite:/app
      - ./Mysite/media:/app/media
      - ./log:/var/log/nginx
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./certbot/www/.well-known/acme-challenge/:/var/www/dehydrated/
    depends_on:
      - web-app
    networks:
      - my_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  my_network:
    driver: bridge