FROM python:3.9

ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
COPY . /app


RUN pip install --upgrade pip
RUN pip install -r requirements_docker.txt

# for entry point
ENTRYPOINT ["sh", "/app/docker-entrypoint-product.sh"]
RUN chmod +x /app/docker-entrypoint-product.sh